---
title: "Domain-Specific Repositories"
---

This document will report on domain-specific repositories that have been used for research
projects at the Rice Rivers Center. Its sister document, the [Data Repository Comparison 
Chart](repoChart.qmd), 
focuses on common, generalist data repositories for depositing your research data products. It can be preferred
to deposit your data in a domain-specific repository for if your data falls within a specific specialty
that has a dedicated repository with community standards and controlled vocabulary. 

The examples below highlight domain-specific repositories that have been used by researchers
at RRC.

# Categories

### Spectroscopy

#### [EcoSIS - Ecological Spectral Information System](https://ecosis.org/)

* An open spectral library that provides access to complete, high quality spectral data sets. 
* Created by several universities with NASA support and maintained by University of
Wisconsin's EnSpec Lab.
* Datasets are eligible to receive a DOI, providing persistent access across the user
community. 
